// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("BusinessLogic.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            City = "Port Jose",
                            Country = "United States",
                            FirstLine = "Viviane Bypass",
                            SecondLine = "710",
                            State = "Arizona",
                            ZipCode = "08155-1760"
                        },
                        new
                        {
                            Id = 102,
                            City = "Lorainefort",
                            Country = "United States",
                            FirstLine = "Dietrich Island",
                            SecondLine = "90198",
                            State = "Tennessee",
                            ZipCode = "79778"
                        },
                        new
                        {
                            Id = 103,
                            City = "New Tyriqueshire",
                            Country = "United States",
                            FirstLine = "Lenna Spring",
                            SecondLine = "9798",
                            State = "Pennsylvania",
                            ZipCode = "84769"
                        },
                        new
                        {
                            Id = 104,
                            City = "West Katherine",
                            Country = "United States",
                            FirstLine = "Brekke Trail",
                            SecondLine = "97411",
                            State = "Pennsylvania",
                            ZipCode = "85416"
                        },
                        new
                        {
                            Id = 105,
                            City = "Tyshawnhaven",
                            Country = "United States",
                            FirstLine = "Felicita Brooks",
                            SecondLine = "83978",
                            State = "Wisconsin",
                            ZipCode = "80712"
                        },
                        new
                        {
                            Id = 106,
                            City = "South Russelmouth",
                            Country = "United States",
                            FirstLine = "Schmidt Orchard",
                            SecondLine = "7380",
                            State = "Massachusetts",
                            ZipCode = "12579"
                        },
                        new
                        {
                            Id = 107,
                            City = "Hannaburgh",
                            Country = "United States",
                            FirstLine = "Willms Brooks",
                            SecondLine = "542",
                            State = "West Virginia",
                            ZipCode = "13138"
                        },
                        new
                        {
                            Id = 108,
                            City = "North Christ",
                            Country = "United States",
                            FirstLine = "Schinner Forks",
                            SecondLine = "027",
                            State = "Nevada",
                            ZipCode = "89228-1378"
                        },
                        new
                        {
                            Id = 109,
                            City = "New Bryceville",
                            Country = "United States",
                            FirstLine = "Brandyn Mount",
                            SecondLine = "482",
                            State = "Alabama",
                            ZipCode = "48409"
                        },
                        new
                        {
                            Id = 110,
                            City = "Lake Bridget",
                            Country = "United States",
                            FirstLine = "Gleason Run",
                            SecondLine = "2606",
                            State = "Louisiana",
                            ZipCode = "85086"
                        },
                        new
                        {
                            Id = 111,
                            City = "South Jamar",
                            Country = "United States",
                            FirstLine = "Beatty Park",
                            SecondLine = "5130",
                            State = "Nebraska",
                            ZipCode = "77264"
                        },
                        new
                        {
                            Id = 112,
                            City = "Port Ernesto",
                            Country = "United States",
                            FirstLine = "Javonte Trail",
                            SecondLine = "685",
                            State = "Washington",
                            ZipCode = "43617"
                        },
                        new
                        {
                            Id = 113,
                            City = "South Brice",
                            Country = "United States",
                            FirstLine = "Harry Freeway",
                            SecondLine = "512",
                            State = "Oregon",
                            ZipCode = "36920"
                        },
                        new
                        {
                            Id = 114,
                            City = "East Adanland",
                            Country = "United States",
                            FirstLine = "Hermiston Spurs",
                            SecondLine = "378",
                            State = "Wyoming",
                            ZipCode = "19206"
                        },
                        new
                        {
                            Id = 115,
                            City = "Ramiroland",
                            Country = "United States",
                            FirstLine = "Hessel Shores",
                            SecondLine = "2641",
                            State = "North Carolina",
                            ZipCode = "91332-3867"
                        },
                        new
                        {
                            Id = 116,
                            City = "East Trentville",
                            Country = "United States",
                            FirstLine = "Merl Lights",
                            SecondLine = "03408",
                            State = "Utah",
                            ZipCode = "40142"
                        },
                        new
                        {
                            Id = 117,
                            City = "Madilynside",
                            Country = "United States",
                            FirstLine = "Blanda Tunnel",
                            SecondLine = "3187",
                            State = "Idaho",
                            ZipCode = "09001"
                        },
                        new
                        {
                            Id = 118,
                            City = "Rippinberg",
                            Country = "United States",
                            FirstLine = "Boyer Port",
                            SecondLine = "903",
                            State = "Wyoming",
                            ZipCode = "22347-3898"
                        },
                        new
                        {
                            Id = 119,
                            City = "Grahamview",
                            Country = "United States",
                            FirstLine = "Kuhlman Rest",
                            SecondLine = "11091",
                            State = "West Virginia",
                            ZipCode = "36208-1546"
                        },
                        new
                        {
                            Id = 120,
                            City = "Daleton",
                            Country = "United States",
                            FirstLine = "Schmeler Locks",
                            SecondLine = "863",
                            State = "Idaho",
                            ZipCode = "69489-3863"
                        },
                        new
                        {
                            Id = 121,
                            City = "North Onieborough",
                            Country = "United States",
                            FirstLine = "Kuhlman Forges",
                            SecondLine = "084",
                            State = "Montana",
                            ZipCode = "94741-3720"
                        },
                        new
                        {
                            Id = 122,
                            City = "Skileschester",
                            Country = "United States",
                            FirstLine = "Melvina Trail",
                            SecondLine = "682",
                            State = "South Dakota",
                            ZipCode = "03298"
                        },
                        new
                        {
                            Id = 123,
                            City = "Carterview",
                            Country = "United States",
                            FirstLine = "Waelchi Lights",
                            SecondLine = "39170",
                            State = "Colorado",
                            ZipCode = "81615-8215"
                        },
                        new
                        {
                            Id = 124,
                            City = "Jovanybury",
                            Country = "United States",
                            FirstLine = "Borer Views",
                            SecondLine = "6581",
                            State = "Nebraska",
                            ZipCode = "78087-9691"
                        },
                        new
                        {
                            Id = 125,
                            City = "Breannamouth",
                            Country = "United States",
                            FirstLine = "Mikayla Dam",
                            SecondLine = "241",
                            State = "North Carolina",
                            ZipCode = "41324"
                        },
                        new
                        {
                            Id = 126,
                            City = "Lake Brooklyn",
                            Country = "United States",
                            FirstLine = "Charlie Springs",
                            SecondLine = "9700",
                            State = "Oregon",
                            ZipCode = "35685"
                        },
                        new
                        {
                            Id = 127,
                            City = "Swaniawskiport",
                            Country = "United States",
                            FirstLine = "Jeff Shore",
                            SecondLine = "4083",
                            State = "Kentucky",
                            ZipCode = "65274-1559"
                        },
                        new
                        {
                            Id = 128,
                            City = "New Lolitamouth",
                            Country = "United States",
                            FirstLine = "Sincere Tunnel",
                            SecondLine = "0902",
                            State = "Florida",
                            ZipCode = "78777-5815"
                        },
                        new
                        {
                            Id = 129,
                            City = "East Eugeniahaven",
                            Country = "United States",
                            FirstLine = "Boehm Mount",
                            SecondLine = "85053",
                            State = "Minnesota",
                            ZipCode = "99367-8614"
                        },
                        new
                        {
                            Id = 130,
                            City = "North Fayeside",
                            Country = "United States",
                            FirstLine = "McClure Street",
                            SecondLine = "370",
                            State = "Montana",
                            ZipCode = "72600-3594"
                        },
                        new
                        {
                            Id = 131,
                            City = "New Edison",
                            Country = "United States",
                            FirstLine = "Kling Trail",
                            SecondLine = "812",
                            State = "Vermont",
                            ZipCode = "32731"
                        },
                        new
                        {
                            Id = 132,
                            City = "North Maymouth",
                            Country = "United States",
                            FirstLine = "Walsh Dam",
                            SecondLine = "55341",
                            State = "Maryland",
                            ZipCode = "53738-6898"
                        },
                        new
                        {
                            Id = 133,
                            City = "Theronmouth",
                            Country = "United States",
                            FirstLine = "Orn Plains",
                            SecondLine = "4398",
                            State = "New Jersey",
                            ZipCode = "13952-6026"
                        },
                        new
                        {
                            Id = 134,
                            City = "Maritzashire",
                            Country = "United States",
                            FirstLine = "Turcotte Field",
                            SecondLine = "0435",
                            State = "Kansas",
                            ZipCode = "89608-1108"
                        },
                        new
                        {
                            Id = 135,
                            City = "Mooreside",
                            Country = "United States",
                            FirstLine = "Blick Springs",
                            SecondLine = "44232",
                            State = "Pennsylvania",
                            ZipCode = "48345-1306"
                        },
                        new
                        {
                            Id = 136,
                            City = "Blockfurt",
                            Country = "United States",
                            FirstLine = "Green Manors",
                            SecondLine = "828",
                            State = "Arkansas",
                            ZipCode = "17708"
                        },
                        new
                        {
                            Id = 137,
                            City = "South Magalifurt",
                            Country = "United States",
                            FirstLine = "Deon Mall",
                            SecondLine = "77012",
                            State = "Texas",
                            ZipCode = "54389"
                        },
                        new
                        {
                            Id = 138,
                            City = "East Braulio",
                            Country = "United States",
                            FirstLine = "Hudson Circles",
                            SecondLine = "0526",
                            State = "Montana",
                            ZipCode = "69155"
                        },
                        new
                        {
                            Id = 139,
                            City = "South Ricardostad",
                            Country = "United States",
                            FirstLine = "Murphy Key",
                            SecondLine = "503",
                            State = "North Dakota",
                            ZipCode = "49147-1101"
                        },
                        new
                        {
                            Id = 140,
                            City = "North Tyree",
                            Country = "United States",
                            FirstLine = "Jast Rue",
                            SecondLine = "00209",
                            State = "New Jersey",
                            ZipCode = "56890"
                        },
                        new
                        {
                            Id = 141,
                            City = "North Thomasview",
                            Country = "United States",
                            FirstLine = "Boyer Lane",
                            SecondLine = "76652",
                            State = "Montana",
                            ZipCode = "19050-3949"
                        },
                        new
                        {
                            Id = 142,
                            City = "Dickiton",
                            Country = "United States",
                            FirstLine = "Mae Roads",
                            SecondLine = "767",
                            State = "Florida",
                            ZipCode = "03943"
                        },
                        new
                        {
                            Id = 143,
                            City = "North Kavonstad",
                            Country = "United States",
                            FirstLine = "Wilhelmine Summit",
                            SecondLine = "454",
                            State = "Kentucky",
                            ZipCode = "78658-1888"
                        },
                        new
                        {
                            Id = 144,
                            City = "New Brayanland",
                            Country = "United States",
                            FirstLine = "Jones Field",
                            SecondLine = "334",
                            State = "Oregon",
                            ZipCode = "95171-2860"
                        },
                        new
                        {
                            Id = 145,
                            City = "Lefflerport",
                            Country = "United States",
                            FirstLine = "Lavinia Forks",
                            SecondLine = "2354",
                            State = "New Hampshire",
                            ZipCode = "45710"
                        },
                        new
                        {
                            Id = 146,
                            City = "West Carletontown",
                            Country = "United States",
                            FirstLine = "Bode Trail",
                            SecondLine = "1289",
                            State = "New Jersey",
                            ZipCode = "25264"
                        },
                        new
                        {
                            Id = 147,
                            City = "New Brandt",
                            Country = "United States",
                            FirstLine = "Boehm Common",
                            SecondLine = "2362",
                            State = "New Jersey",
                            ZipCode = "92251"
                        },
                        new
                        {
                            Id = 148,
                            City = "Watsicaview",
                            Country = "United States",
                            FirstLine = "Jerde Causeway",
                            SecondLine = "3222",
                            State = "Kansas",
                            ZipCode = "19210-4661"
                        },
                        new
                        {
                            Id = 149,
                            City = "Robertsbury",
                            Country = "United States",
                            FirstLine = "Wyman Mission",
                            SecondLine = "07103",
                            State = "New Jersey",
                            ZipCode = "44782"
                        },
                        new
                        {
                            Id = 150,
                            City = "Noemimouth",
                            Country = "United States",
                            FirstLine = "Kiana Rapid",
                            SecondLine = "099",
                            State = "Hawaii",
                            ZipCode = "85580-0024"
                        },
                        new
                        {
                            Id = 151,
                            City = "Rogersmouth",
                            Country = "United States",
                            FirstLine = "Margaretta Neck",
                            SecondLine = "535",
                            State = "Indiana",
                            ZipCode = "36582-4301"
                        },
                        new
                        {
                            Id = 152,
                            City = "West Giuseppe",
                            Country = "United States",
                            FirstLine = "Everett Estate",
                            SecondLine = "880",
                            State = "North Dakota",
                            ZipCode = "88810-4549"
                        },
                        new
                        {
                            Id = 153,
                            City = "Milesberg",
                            Country = "United States",
                            FirstLine = "Ziemann Views",
                            SecondLine = "59998",
                            State = "Iowa",
                            ZipCode = "33774-5343"
                        },
                        new
                        {
                            Id = 154,
                            City = "Lake Lorenzaberg",
                            Country = "United States",
                            FirstLine = "Batz Parks",
                            SecondLine = "671",
                            State = "Minnesota",
                            ZipCode = "27380"
                        },
                        new
                        {
                            Id = 155,
                            City = "Odessaburgh",
                            Country = "United States",
                            FirstLine = "John Summit",
                            SecondLine = "351",
                            State = "Pennsylvania",
                            ZipCode = "95463"
                        },
                        new
                        {
                            Id = 156,
                            City = "East Wilfridland",
                            Country = "United States",
                            FirstLine = "Tressa Forges",
                            SecondLine = "16495",
                            State = "Alabama",
                            ZipCode = "54995"
                        },
                        new
                        {
                            Id = 157,
                            City = "Mozellchester",
                            Country = "United States",
                            FirstLine = "Osinski Camp",
                            SecondLine = "0992",
                            State = "Alaska",
                            ZipCode = "86467-2839"
                        },
                        new
                        {
                            Id = 158,
                            City = "South Isac",
                            Country = "United States",
                            FirstLine = "Kozey Trafficway",
                            SecondLine = "6235",
                            State = "Colorado",
                            ZipCode = "48611-7238"
                        },
                        new
                        {
                            Id = 159,
                            City = "East Marcellehaven",
                            Country = "United States",
                            FirstLine = "Deontae Forks",
                            SecondLine = "49967",
                            State = "New Hampshire",
                            ZipCode = "53691-2155"
                        },
                        new
                        {
                            Id = 160,
                            City = "New Troyland",
                            Country = "United States",
                            FirstLine = "Branson Mission",
                            SecondLine = "601",
                            State = "New Mexico",
                            ZipCode = "48458"
                        },
                        new
                        {
                            Id = 161,
                            City = "West Cydneystad",
                            Country = "United States",
                            FirstLine = "Harris Ville",
                            SecondLine = "53068",
                            State = "Hawaii",
                            ZipCode = "60240-0790"
                        },
                        new
                        {
                            Id = 162,
                            City = "West Delpha",
                            Country = "United States",
                            FirstLine = "Trudie Lock",
                            SecondLine = "19845",
                            State = "North Carolina",
                            ZipCode = "51991"
                        },
                        new
                        {
                            Id = 163,
                            City = "South Shaniyaland",
                            Country = "United States",
                            FirstLine = "Russell Lock",
                            SecondLine = "99635",
                            State = "Maine",
                            ZipCode = "06895-9286"
                        },
                        new
                        {
                            Id = 164,
                            City = "Scotland",
                            Country = "United States",
                            FirstLine = "Tiffany Landing",
                            SecondLine = "87200",
                            State = "Nevada",
                            ZipCode = "51552-4941"
                        },
                        new
                        {
                            Id = 165,
                            City = "Lake Alexandria",
                            Country = "United States",
                            FirstLine = "Powlowski Estate",
                            SecondLine = "303",
                            State = "Pennsylvania",
                            ZipCode = "95658"
                        },
                        new
                        {
                            Id = 166,
                            City = "Lake Abbie",
                            Country = "United States",
                            FirstLine = "Kunde Spurs",
                            SecondLine = "4740",
                            State = "Maryland",
                            ZipCode = "37775"
                        },
                        new
                        {
                            Id = 167,
                            City = "North Presleymouth",
                            Country = "United States",
                            FirstLine = "Lucinda Trace",
                            SecondLine = "062",
                            State = "New Hampshire",
                            ZipCode = "89374-6539"
                        },
                        new
                        {
                            Id = 168,
                            City = "East Willie",
                            Country = "United States",
                            FirstLine = "Sipes Walks",
                            SecondLine = "38860",
                            State = "Kentucky",
                            ZipCode = "98403-4665"
                        },
                        new
                        {
                            Id = 169,
                            City = "East Hermanside",
                            Country = "United States",
                            FirstLine = "Emard Crossing",
                            SecondLine = "6621",
                            State = "Alaska",
                            ZipCode = "82314-7236"
                        },
                        new
                        {
                            Id = 170,
                            City = "Farrellton",
                            Country = "United States",
                            FirstLine = "Bartell Light",
                            SecondLine = "051",
                            State = "Kansas",
                            ZipCode = "92420"
                        },
                        new
                        {
                            Id = 171,
                            City = "Lindfort",
                            Country = "United States",
                            FirstLine = "Dibbert Walk",
                            SecondLine = "809",
                            State = "Wisconsin",
                            ZipCode = "28235"
                        },
                        new
                        {
                            Id = 172,
                            City = "East Rogeliochester",
                            Country = "United States",
                            FirstLine = "Hudson Drives",
                            SecondLine = "250",
                            State = "Pennsylvania",
                            ZipCode = "09940-0476"
                        },
                        new
                        {
                            Id = 173,
                            City = "North Ritabury",
                            Country = "United States",
                            FirstLine = "Jessica Club",
                            SecondLine = "7260",
                            State = "North Carolina",
                            ZipCode = "03569"
                        },
                        new
                        {
                            Id = 174,
                            City = "Stromanberg",
                            Country = "United States",
                            FirstLine = "Prohaska Estate",
                            SecondLine = "06703",
                            State = "Wyoming",
                            ZipCode = "93667-7851"
                        },
                        new
                        {
                            Id = 175,
                            City = "West Janie",
                            Country = "United States",
                            FirstLine = "Orn Valleys",
                            SecondLine = "3881",
                            State = "Delaware",
                            ZipCode = "82080-1213"
                        },
                        new
                        {
                            Id = 176,
                            City = "Wisokyland",
                            Country = "United States",
                            FirstLine = "Stanton Park",
                            SecondLine = "636",
                            State = "Alaska",
                            ZipCode = "55103-1473"
                        },
                        new
                        {
                            Id = 177,
                            City = "Ellisshire",
                            Country = "United States",
                            FirstLine = "Langworth Ports",
                            SecondLine = "53686",
                            State = "Kansas",
                            ZipCode = "09614-4643"
                        },
                        new
                        {
                            Id = 178,
                            City = "Schneiderport",
                            Country = "United States",
                            FirstLine = "Hildegard Glens",
                            SecondLine = "876",
                            State = "Washington",
                            ZipCode = "39619-0934"
                        },
                        new
                        {
                            Id = 179,
                            City = "Port Devontemouth",
                            Country = "United States",
                            FirstLine = "Langworth Flat",
                            SecondLine = "016",
                            State = "Michigan",
                            ZipCode = "55267"
                        },
                        new
                        {
                            Id = 180,
                            City = "North Albertoport",
                            Country = "United States",
                            FirstLine = "Wyatt Prairie",
                            SecondLine = "5387",
                            State = "Massachusetts",
                            ZipCode = "19390-0769"
                        },
                        new
                        {
                            Id = 181,
                            City = "East Ursula",
                            Country = "United States",
                            FirstLine = "Shanahan Ford",
                            SecondLine = "51308",
                            State = "Kansas",
                            ZipCode = "20883-0604"
                        },
                        new
                        {
                            Id = 182,
                            City = "Port Mekhi",
                            Country = "United States",
                            FirstLine = "Brekke Harbor",
                            SecondLine = "16169",
                            State = "North Dakota",
                            ZipCode = "22569"
                        },
                        new
                        {
                            Id = 183,
                            City = "Feeneyland",
                            Country = "United States",
                            FirstLine = "Clotilde Crescent",
                            SecondLine = "711",
                            State = "Minnesota",
                            ZipCode = "39330-2924"
                        },
                        new
                        {
                            Id = 184,
                            City = "Lorafort",
                            Country = "United States",
                            FirstLine = "O'Hara Glen",
                            SecondLine = "3057",
                            State = "Maine",
                            ZipCode = "82745-1979"
                        },
                        new
                        {
                            Id = 185,
                            City = "Millerview",
                            Country = "United States",
                            FirstLine = "Littel Shore",
                            SecondLine = "7381",
                            State = "Nebraska",
                            ZipCode = "58140"
                        },
                        new
                        {
                            Id = 186,
                            City = "New Madisynchester",
                            Country = "United States",
                            FirstLine = "Crooks Pines",
                            SecondLine = "6250",
                            State = "Tennessee",
                            ZipCode = "67178"
                        },
                        new
                        {
                            Id = 187,
                            City = "Dietrichbury",
                            Country = "United States",
                            FirstLine = "Harvey Forest",
                            SecondLine = "461",
                            State = "Oregon",
                            ZipCode = "20036-3085"
                        },
                        new
                        {
                            Id = 188,
                            City = "Howardton",
                            Country = "United States",
                            FirstLine = "Mabelle Flat",
                            SecondLine = "42729",
                            State = "Iowa",
                            ZipCode = "63318-4346"
                        },
                        new
                        {
                            Id = 189,
                            City = "North Roxane",
                            Country = "United States",
                            FirstLine = "Nichole Islands",
                            SecondLine = "780",
                            State = "Kansas",
                            ZipCode = "60593-4726"
                        },
                        new
                        {
                            Id = 190,
                            City = "East Major",
                            Country = "United States",
                            FirstLine = "Ova Well",
                            SecondLine = "30222",
                            State = "West Virginia",
                            ZipCode = "51503-8332"
                        },
                        new
                        {
                            Id = 191,
                            City = "North Arleneshire",
                            Country = "United States",
                            FirstLine = "Dooley Bridge",
                            SecondLine = "71406",
                            State = "Maine",
                            ZipCode = "38718"
                        },
                        new
                        {
                            Id = 192,
                            City = "Jacobiborough",
                            Country = "United States",
                            FirstLine = "Brant View",
                            SecondLine = "108",
                            State = "Massachusetts",
                            ZipCode = "95003"
                        },
                        new
                        {
                            Id = 193,
                            City = "Sanfordmouth",
                            Country = "United States",
                            FirstLine = "Marks Corners",
                            SecondLine = "355",
                            State = "Pennsylvania",
                            ZipCode = "65115"
                        },
                        new
                        {
                            Id = 194,
                            City = "New Lydia",
                            Country = "United States",
                            FirstLine = "Stehr Fort",
                            SecondLine = "16266",
                            State = "Florida",
                            ZipCode = "33901"
                        },
                        new
                        {
                            Id = 195,
                            City = "New Mozellefort",
                            Country = "United States",
                            FirstLine = "Bethany Brooks",
                            SecondLine = "3735",
                            State = "Idaho",
                            ZipCode = "37170"
                        },
                        new
                        {
                            Id = 196,
                            City = "West Reganfurt",
                            Country = "United States",
                            FirstLine = "Ward Street",
                            SecondLine = "73836",
                            State = "Minnesota",
                            ZipCode = "14828"
                        },
                        new
                        {
                            Id = 197,
                            City = "Rennerville",
                            Country = "United States",
                            FirstLine = "Sauer Club",
                            SecondLine = "09444",
                            State = "Nevada",
                            ZipCode = "52202-2547"
                        },
                        new
                        {
                            Id = 198,
                            City = "Waelchimouth",
                            Country = "United States",
                            FirstLine = "Nettie Station",
                            SecondLine = "32098",
                            State = "Pennsylvania",
                            ZipCode = "70883-8831"
                        },
                        new
                        {
                            Id = 199,
                            City = "West Angelitatown",
                            Country = "United States",
                            FirstLine = "Nyasia Turnpike",
                            SecondLine = "935",
                            State = "New York",
                            ZipCode = "28124"
                        },
                        new
                        {
                            Id = 200,
                            City = "West Furmanville",
                            Country = "United States",
                            FirstLine = "Sipes Inlet",
                            SecondLine = "3735",
                            State = "New York",
                            ZipCode = "05524-4063"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AddressId = 101,
                            CompanyName = "Russel, Nienow and Schaefer",
                            Name = "Casey",
                            PhoneNumber = "(886) 550-0543",
                            Surname = "Schultz"
                        },
                        new
                        {
                            Id = 102,
                            AddressId = 102,
                            CompanyName = "Farrell - Mohr",
                            Name = "Meaghan",
                            PhoneNumber = "(661) 400-4168 x761",
                            Surname = "Jenkins"
                        },
                        new
                        {
                            Id = 103,
                            AddressId = 103,
                            CompanyName = "Rogahn - Predovic",
                            Name = "Jackson",
                            PhoneNumber = "678-563-3006",
                            Surname = "Mann"
                        },
                        new
                        {
                            Id = 104,
                            AddressId = 104,
                            CompanyName = "Windler - Ebert",
                            Name = "Dillon",
                            PhoneNumber = "1-662-689-7962",
                            Surname = "Gottlieb"
                        },
                        new
                        {
                            Id = 105,
                            AddressId = 105,
                            CompanyName = "Jacobi - Schamberger",
                            Name = "Leanna",
                            PhoneNumber = "280.773.9869 x4429",
                            Surname = "Volkman"
                        },
                        new
                        {
                            Id = 106,
                            AddressId = 106,
                            CompanyName = "Hilpert - Stiedemann",
                            Name = "Jermaine",
                            PhoneNumber = "826.478.2499",
                            Surname = "Ebert"
                        },
                        new
                        {
                            Id = 107,
                            AddressId = 107,
                            CompanyName = "Keeling LLC",
                            Name = "Maxine",
                            PhoneNumber = "1-531-358-5852 x776",
                            Surname = "Walker"
                        },
                        new
                        {
                            Id = 108,
                            AddressId = 108,
                            CompanyName = "Lindgren and Sons",
                            Name = "Giovanna",
                            PhoneNumber = "813.681.5877 x97500",
                            Surname = "Reichel"
                        },
                        new
                        {
                            Id = 109,
                            AddressId = 109,
                            CompanyName = "Nienow, Bradtke and Bartell",
                            Name = "Marcelle",
                            PhoneNumber = "(441) 347-9390 x9710",
                            Surname = "Wolff"
                        },
                        new
                        {
                            Id = 110,
                            AddressId = 110,
                            CompanyName = "Swaniawski LLC",
                            Name = "Anais",
                            PhoneNumber = "855-217-6091",
                            Surname = "Wisozk"
                        },
                        new
                        {
                            Id = 111,
                            AddressId = 111,
                            CompanyName = "Bechtelar - Wuckert",
                            Name = "Anderson",
                            PhoneNumber = "968.783.7977 x80675",
                            Surname = "Cole"
                        },
                        new
                        {
                            Id = 112,
                            AddressId = 112,
                            CompanyName = "Prohaska, Wilkinson and Stiedemann",
                            Name = "Dell",
                            PhoneNumber = "1-918-847-6971 x83974",
                            Surname = "Nitzsche"
                        },
                        new
                        {
                            Id = 113,
                            AddressId = 113,
                            CompanyName = "Dickens and Sons",
                            Name = "Geoffrey",
                            PhoneNumber = "554.916.3302 x8397",
                            Surname = "Lowe"
                        },
                        new
                        {
                            Id = 114,
                            AddressId = 114,
                            CompanyName = "Raynor, West and Strosin",
                            Name = "Wade",
                            PhoneNumber = "212-778-5573 x80158",
                            Surname = "Grady"
                        },
                        new
                        {
                            Id = 115,
                            AddressId = 115,
                            CompanyName = "Jacobs - Heller",
                            Name = "Carmella",
                            PhoneNumber = "799.909.5426 x429",
                            Surname = "Greenfelder"
                        },
                        new
                        {
                            Id = 116,
                            AddressId = 116,
                            CompanyName = "D'Amore - Huel",
                            Name = "Clementina",
                            PhoneNumber = "828-802-7201 x55892",
                            Surname = "Heller"
                        },
                        new
                        {
                            Id = 117,
                            AddressId = 117,
                            CompanyName = "Schumm Inc",
                            Name = "Eryn",
                            PhoneNumber = "257-348-2161 x20348",
                            Surname = "Runolfsdottir"
                        },
                        new
                        {
                            Id = 118,
                            AddressId = 118,
                            CompanyName = "Borer - Wolf",
                            Name = "Maymie",
                            PhoneNumber = "1-660-362-7132 x8508",
                            Surname = "Gleason"
                        },
                        new
                        {
                            Id = 119,
                            AddressId = 119,
                            CompanyName = "Rippin, Beatty and MacGyver",
                            Name = "Horacio",
                            PhoneNumber = "1-435-245-4772",
                            Surname = "Lebsack"
                        },
                        new
                        {
                            Id = 120,
                            AddressId = 120,
                            CompanyName = "Kutch - Bergstrom",
                            Name = "Javonte",
                            PhoneNumber = "754-893-9343 x61704",
                            Surname = "Tillman"
                        },
                        new
                        {
                            Id = 121,
                            AddressId = 121,
                            CompanyName = "Roberts LLC",
                            Name = "Ciara",
                            PhoneNumber = "673.336.9209",
                            Surname = "Doyle"
                        },
                        new
                        {
                            Id = 122,
                            AddressId = 122,
                            CompanyName = "Schaden - Veum",
                            Name = "Fredy",
                            PhoneNumber = "(201) 391-1920 x67374",
                            Surname = "Quigley"
                        },
                        new
                        {
                            Id = 123,
                            AddressId = 123,
                            CompanyName = "Pagac and Sons",
                            Name = "Berta",
                            PhoneNumber = "379-713-3238 x67374",
                            Surname = "Reichel"
                        },
                        new
                        {
                            Id = 124,
                            AddressId = 124,
                            CompanyName = "Boyle and Sons",
                            Name = "Jamil",
                            PhoneNumber = "292-483-4014 x29085",
                            Surname = "Altenwerth"
                        },
                        new
                        {
                            Id = 125,
                            AddressId = 125,
                            CompanyName = "Cummings Group",
                            Name = "Ona",
                            PhoneNumber = "(900) 390-0150 x6790",
                            Surname = "Reinger"
                        },
                        new
                        {
                            Id = 126,
                            AddressId = 126,
                            CompanyName = "Runolfsson - Rippin",
                            Name = "Dasia",
                            PhoneNumber = "1-334-373-8989 x46211",
                            Surname = "Zulauf"
                        },
                        new
                        {
                            Id = 127,
                            AddressId = 127,
                            CompanyName = "VonRueden Inc",
                            Name = "Stanley",
                            PhoneNumber = "936-620-8154 x677",
                            Surname = "Graham"
                        },
                        new
                        {
                            Id = 128,
                            AddressId = 128,
                            CompanyName = "Padberg - Stark",
                            Name = "Leann",
                            PhoneNumber = "(326) 269-4893 x8637",
                            Surname = "Hickle"
                        },
                        new
                        {
                            Id = 129,
                            AddressId = 129,
                            CompanyName = "Funk - Ratke",
                            Name = "Alexander",
                            PhoneNumber = "373-258-9474 x137",
                            Surname = "Schneider"
                        },
                        new
                        {
                            Id = 130,
                            AddressId = 130,
                            CompanyName = "Berge and Sons",
                            Name = "Melvina",
                            PhoneNumber = "1-729-886-8303 x2987",
                            Surname = "Tillman"
                        },
                        new
                        {
                            Id = 131,
                            AddressId = 131,
                            CompanyName = "Kessler, Emmerich and Harber",
                            Name = "Sterling",
                            PhoneNumber = "214.915.8161 x5821",
                            Surname = "Considine"
                        },
                        new
                        {
                            Id = 132,
                            AddressId = 132,
                            CompanyName = "Witting - Borer",
                            Name = "Trisha",
                            PhoneNumber = "(615) 853-5878 x0879",
                            Surname = "O'Connell"
                        },
                        new
                        {
                            Id = 133,
                            AddressId = 133,
                            CompanyName = "Upton - Collier",
                            Name = "Jensen",
                            PhoneNumber = "941.361.5634",
                            Surname = "Raynor"
                        },
                        new
                        {
                            Id = 134,
                            AddressId = 134,
                            CompanyName = "Hudson and Sons",
                            Name = "Jacinto",
                            PhoneNumber = "897.600.3817",
                            Surname = "Feest"
                        },
                        new
                        {
                            Id = 135,
                            AddressId = 135,
                            CompanyName = "Hand LLC",
                            Name = "Marlon",
                            PhoneNumber = "373.540.8388 x537",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 136,
                            AddressId = 136,
                            CompanyName = "Lueilwitz - Grady",
                            Name = "Myah",
                            PhoneNumber = "1-691-688-6090",
                            Surname = "Kilback"
                        },
                        new
                        {
                            Id = 137,
                            AddressId = 137,
                            CompanyName = "Cassin LLC",
                            Name = "Lolita",
                            PhoneNumber = "887.777.5815",
                            Surname = "Legros"
                        },
                        new
                        {
                            Id = 138,
                            AddressId = 138,
                            CompanyName = "Boehm, Lebsack and Deckow",
                            Name = "Rashawn",
                            PhoneNumber = "(602) 438-4899",
                            Surname = "McDermott"
                        },
                        new
                        {
                            Id = 139,
                            AddressId = 139,
                            CompanyName = "Nitzsche - Rogahn",
                            Name = "Sabrina",
                            PhoneNumber = "558.873.7000",
                            Surname = "Predovic"
                        },
                        new
                        {
                            Id = 140,
                            AddressId = 140,
                            CompanyName = "Ullrich - Leannon",
                            Name = "Jewell",
                            PhoneNumber = "603-259-4848",
                            Surname = "Roberts"
                        },
                        new
                        {
                            Id = 141,
                            AddressId = 141,
                            CompanyName = "Steuber, Corwin and Friesen",
                            Name = "Gino",
                            PhoneNumber = "(932) 273-1591",
                            Surname = "Parker"
                        },
                        new
                        {
                            Id = 142,
                            AddressId = 142,
                            CompanyName = "Langosh LLC",
                            Name = "Erna",
                            PhoneNumber = "377.236.5373",
                            Surname = "Kub"
                        },
                        new
                        {
                            Id = 143,
                            AddressId = 143,
                            CompanyName = "Mitchell, Towne and Waters",
                            Name = "Rogelio",
                            PhoneNumber = "(643) 798-6975 x7139",
                            Surname = "Mueller"
                        },
                        new
                        {
                            Id = 144,
                            AddressId = 144,
                            CompanyName = "Greenfelder - Parker",
                            Name = "Adrain",
                            PhoneNumber = "(925) 904-3556 x9378",
                            Surname = "Farrell"
                        },
                        new
                        {
                            Id = 145,
                            AddressId = 145,
                            CompanyName = "Price, Bechtelar and Simonis",
                            Name = "Camylle",
                            PhoneNumber = "807-724-4232",
                            Surname = "Cormier"
                        },
                        new
                        {
                            Id = 146,
                            AddressId = 146,
                            CompanyName = "Moore, Watsica and Romaguera",
                            Name = "Millie",
                            PhoneNumber = "(451) 530-6434 x98288",
                            Surname = "Jenkins"
                        },
                        new
                        {
                            Id = 147,
                            AddressId = 147,
                            CompanyName = "Padberg Inc",
                            Name = "Dereck",
                            PhoneNumber = "882.224.0770 x1215",
                            Surname = "Connelly"
                        },
                        new
                        {
                            Id = 148,
                            AddressId = 148,
                            CompanyName = "Nikolaus - Stamm",
                            Name = "Jeanne",
                            PhoneNumber = "(494) 840-3052 x642",
                            Surname = "McKenzie"
                        },
                        new
                        {
                            Id = 149,
                            AddressId = 149,
                            CompanyName = "Larkin and Sons",
                            Name = "Leon",
                            PhoneNumber = "1-676-637-5032",
                            Surname = "Weber"
                        },
                        new
                        {
                            Id = 150,
                            AddressId = 150,
                            CompanyName = "Simonis - McCullough",
                            Name = "Mallory",
                            PhoneNumber = "947-311-0154 x700",
                            Surname = "Orn"
                        },
                        new
                        {
                            Id = 151,
                            AddressId = 151,
                            CompanyName = "Frami Inc",
                            Name = "Tanner",
                            PhoneNumber = "925-668-9080",
                            Surname = "Homenick"
                        },
                        new
                        {
                            Id = 152,
                            AddressId = 152,
                            CompanyName = "Boyle - Schmidt",
                            Name = "Lempi",
                            PhoneNumber = "419.345.5190 x503",
                            Surname = "Pfeffer"
                        },
                        new
                        {
                            Id = 153,
                            AddressId = 153,
                            CompanyName = "Jaskolski, Von and Douglas",
                            Name = "Mae",
                            PhoneNumber = "779-610-1003 x94349",
                            Surname = "Reichert"
                        },
                        new
                        {
                            Id = 154,
                            AddressId = 154,
                            CompanyName = "Rutherford, Koch and Little",
                            Name = "Hollie",
                            PhoneNumber = "1-639-678-6581",
                            Surname = "Bartell"
                        },
                        new
                        {
                            Id = 155,
                            AddressId = 155,
                            CompanyName = "Spencer, Streich and O'Hara",
                            Name = "Helga",
                            PhoneNumber = "1-440-461-1789 x5171",
                            Surname = "Emard"
                        },
                        new
                        {
                            Id = 156,
                            AddressId = 156,
                            CompanyName = "Schumm LLC",
                            Name = "Andreane",
                            PhoneNumber = "423.554.7545 x345",
                            Surname = "Corwin"
                        },
                        new
                        {
                            Id = 157,
                            AddressId = 157,
                            CompanyName = "Dare, Boehm and Lowe",
                            Name = "Arnaldo",
                            PhoneNumber = "(389) 313-1050 x252",
                            Surname = "Thiel"
                        },
                        new
                        {
                            Id = 158,
                            AddressId = 158,
                            CompanyName = "Kovacek - Yundt",
                            Name = "Arnold",
                            PhoneNumber = "(462) 436-1509 x225",
                            Surname = "Bosco"
                        },
                        new
                        {
                            Id = 159,
                            AddressId = 159,
                            CompanyName = "Padberg and Sons",
                            Name = "Amir",
                            PhoneNumber = "1-427-394-3719",
                            Surname = "Lueilwitz"
                        },
                        new
                        {
                            Id = 160,
                            AddressId = 160,
                            CompanyName = "Dickens Inc",
                            Name = "Jacky",
                            PhoneNumber = "395-620-7103 x7745",
                            Surname = "Murphy"
                        },
                        new
                        {
                            Id = 161,
                            AddressId = 161,
                            CompanyName = "Johnson and Sons",
                            Name = "Myriam",
                            PhoneNumber = "267-609-9677",
                            Surname = "Skiles"
                        },
                        new
                        {
                            Id = 162,
                            AddressId = 162,
                            CompanyName = "Schroeder Group",
                            Name = "Kenton",
                            PhoneNumber = "202-241-6575 x35787",
                            Surname = "Lesch"
                        },
                        new
                        {
                            Id = 163,
                            AddressId = 163,
                            CompanyName = "Mueller and Sons",
                            Name = "Lelah",
                            PhoneNumber = "(330) 513-3198 x80333",
                            Surname = "Mante"
                        },
                        new
                        {
                            Id = 164,
                            AddressId = 164,
                            CompanyName = "McCullough - Schumm",
                            Name = "Simone",
                            PhoneNumber = "1-254-599-9915",
                            Surname = "Tromp"
                        },
                        new
                        {
                            Id = 165,
                            AddressId = 165,
                            CompanyName = "Wintheiser, West and Smitham",
                            Name = "Karen",
                            PhoneNumber = "433-777-4534",
                            Surname = "Raynor"
                        },
                        new
                        {
                            Id = 166,
                            AddressId = 166,
                            CompanyName = "Miller - Batz",
                            Name = "Keon",
                            PhoneNumber = "(807) 362-4327 x3804",
                            Surname = "Ratke"
                        },
                        new
                        {
                            Id = 167,
                            AddressId = 167,
                            CompanyName = "Stanton - West",
                            Name = "Freeda",
                            PhoneNumber = "627.819.5463",
                            Surname = "Legros"
                        },
                        new
                        {
                            Id = 168,
                            AddressId = 168,
                            CompanyName = "Wehner Inc",
                            Name = "Elenora",
                            PhoneNumber = "550-929-1035 x4995",
                            Surname = "Dickens"
                        },
                        new
                        {
                            Id = 169,
                            AddressId = 169,
                            CompanyName = "Osinski - Bauch",
                            Name = "Keaton",
                            PhoneNumber = "967.470.7864 x67283",
                            Surname = "Boyle"
                        },
                        new
                        {
                            Id = 170,
                            AddressId = 170,
                            CompanyName = "Schaefer, Kozey and Swaniawski",
                            Name = "Lance",
                            PhoneNumber = "(545) 641-6486",
                            Surname = "Nolan"
                        },
                        new
                        {
                            Id = 171,
                            AddressId = 171,
                            CompanyName = "Donnelly LLC",
                            Name = "Colleen",
                            PhoneNumber = "422-449-9671 x16856",
                            Surname = "Hand"
                        },
                        new
                        {
                            Id = 172,
                            AddressId = 172,
                            CompanyName = "Heidenreich - O'Reilly",
                            Name = "Sydney",
                            PhoneNumber = "352-615-9601",
                            Surname = "Braun"
                        },
                        new
                        {
                            Id = 173,
                            AddressId = 173,
                            CompanyName = "O'Reilly Group",
                            Name = "Blanca",
                            PhoneNumber = "1-545-888-3905",
                            Surname = "Mosciski"
                        },
                        new
                        {
                            Id = 174,
                            AddressId = 174,
                            CompanyName = "Abshire LLC",
                            Name = "Rowland",
                            PhoneNumber = "(326) 660-2400",
                            Surname = "Becker"
                        },
                        new
                        {
                            Id = 175,
                            AddressId = 175,
                            CompanyName = "Wisoky, Altenwerth and Abshire",
                            Name = "Trudie",
                            PhoneNumber = "(384) 953-2261",
                            Surname = "Kirlin"
                        },
                        new
                        {
                            Id = 176,
                            AddressId = 176,
                            CompanyName = "Denesik - Weimann",
                            Name = "Tamia",
                            PhoneNumber = "(839) 596-3505",
                            Surname = "Daugherty"
                        },
                        new
                        {
                            Id = 177,
                            AddressId = 177,
                            CompanyName = "Conn, Hettinger and White",
                            Name = "Adolfo",
                            PhoneNumber = "(992) 686-2940 x87200",
                            Surname = "O'Keefe"
                        },
                        new
                        {
                            Id = 178,
                            AddressId = 178,
                            CompanyName = "Swift - Cremin",
                            Name = "Keanu",
                            PhoneNumber = "1-252-649-4186 x183",
                            Surname = "Mohr"
                        },
                        new
                        {
                            Id = 179,
                            AddressId = 179,
                            CompanyName = "Jacobi and Sons",
                            Name = "Royce",
                            PhoneNumber = "256.958.7476 x4740",
                            Surname = "Bartell"
                        },
                        new
                        {
                            Id = 180,
                            AddressId = 180,
                            CompanyName = "Schultz Inc",
                            Name = "Georgiana",
                            PhoneNumber = "775.836.8906",
                            Surname = "Adams"
                        },
                        new
                        {
                            Id = 181,
                            AddressId = 181,
                            CompanyName = "Aufderhar Inc",
                            Name = "Presley",
                            PhoneNumber = "693.874.6539 x789",
                            Surname = "Lemke"
                        },
                        new
                        {
                            Id = 182,
                            AddressId = 182,
                            CompanyName = "Jacobi Group",
                            Name = "Rosalyn",
                            PhoneNumber = "493-399-8403",
                            Surname = "Pacocha"
                        },
                        new
                        {
                            Id = 183,
                            AddressId = 183,
                            CompanyName = "Osinski - O'Hara",
                            Name = "Jonatan",
                            PhoneNumber = "366-521-2149",
                            Surname = "Roob"
                        },
                        new
                        {
                            Id = 184,
                            AddressId = 184,
                            CompanyName = "Wiza Group",
                            Name = "Elian",
                            PhoneNumber = "523.865.0490",
                            Surname = "Hoppe"
                        },
                        new
                        {
                            Id = 185,
                            AddressId = 185,
                            CompanyName = "Dibbert - Walter",
                            Name = "Dante",
                            PhoneNumber = "1-324-920-7198",
                            Surname = "Blanda"
                        },
                        new
                        {
                            Id = 186,
                            AddressId = 186,
                            CompanyName = "Aufderhar, Watsica and Simonis",
                            Name = "Kaleb",
                            PhoneNumber = "482.335.6317 x25021",
                            Surname = "Schimmel"
                        },
                        new
                        {
                            Id = 187,
                            AddressId = 187,
                            CompanyName = "Rau, Roob and Veum",
                            Name = "Aliya",
                            PhoneNumber = "1-504-276-0405 x72601",
                            Surname = "Walsh"
                        },
                        new
                        {
                            Id = 188,
                            AddressId = 188,
                            CompanyName = "Skiles and Sons",
                            Name = "Madisen",
                            PhoneNumber = "(469) 667-1206",
                            Surname = "Bernhard"
                        },
                        new
                        {
                            Id = 189,
                            AddressId = 189,
                            CompanyName = "Bayer, Hermann and Schowalter",
                            Name = "Sandrine",
                            PhoneNumber = "836.967.7851 x66953",
                            Surname = "Emard"
                        },
                        new
                        {
                            Id = 190,
                            AddressId = 190,
                            CompanyName = "Thiel, Breitenberg and Koss",
                            Name = "Genesis",
                            PhoneNumber = "920.880.1213",
                            Surname = "Kovacek"
                        },
                        new
                        {
                            Id = 191,
                            AddressId = 191,
                            CompanyName = "Stanton, Maggio and Powlowski",
                            Name = "Maryam",
                            PhoneNumber = "(810) 955-5103 x1473",
                            Surname = "Homenick"
                        },
                        new
                        {
                            Id = 192,
                            AddressId = 192,
                            CompanyName = "Langworth, O'Keefe and Bahringer",
                            Name = "Kathleen",
                            PhoneNumber = "863-793-8096 x1446",
                            Surname = "Jacobi"
                        },
                        new
                        {
                            Id = 193,
                            AddressId = 193,
                            CompanyName = "Hickle - Cartwright",
                            Name = "Hildegard",
                            PhoneNumber = "1-869-884-9939 x6190",
                            Surname = "Greenholt"
                        },
                        new
                        {
                            Id = 194,
                            AddressId = 194,
                            CompanyName = "Gutmann, Klocko and Reynolds",
                            Name = "Jonatan",
                            PhoneNumber = "1-260-292-7415 x5267",
                            Surname = "Fadel"
                        },
                        new
                        {
                            Id = 195,
                            AddressId = 195,
                            CompanyName = "Yost LLC",
                            Name = "Jesus",
                            PhoneNumber = "800.705.4619",
                            Surname = "Kuvalis"
                        },
                        new
                        {
                            Id = 196,
                            AddressId = 196,
                            CompanyName = "Von - Bernhard",
                            Name = "Addie",
                            PhoneNumber = "(982) 915-1308 x3293",
                            Surname = "Sawayn"
                        },
                        new
                        {
                            Id = 197,
                            AddressId = 197,
                            CompanyName = "Feest, Anderson and Smitham",
                            Name = "Shirley",
                            PhoneNumber = "(748) 213-2161",
                            Surname = "Hayes"
                        },
                        new
                        {
                            Id = 198,
                            AddressId = 198,
                            CompanyName = "Yost - Hilpert",
                            Name = "Yvonne",
                            PhoneNumber = "(425) 369-1116 x7119",
                            Surname = "Quigley"
                        },
                        new
                        {
                            Id = 199,
                            AddressId = 199,
                            CompanyName = "Carter and Sons",
                            Name = "Lewis",
                            PhoneNumber = "402.492.4662 x53057",
                            Surname = "Harber"
                        },
                        new
                        {
                            Id = 200,
                            AddressId = 200,
                            CompanyName = "Nader - Schiller",
                            Name = "Gaetano",
                            PhoneNumber = "(445) 719-7955 x76738",
                            Surname = "Renner"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Customer", b =>
                {
                    b.HasOne("BusinessLogic.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
